# 1. Install dependencies
FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json ./ 
RUN npm install

# 2. Build Next.js app
FROM node:20-alpine AS builder
WORKDIR /app
COPY . .
COPY --from=deps /app/node_modules ./node_modules
RUN npm run build

# 3. Run production container
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
EXPOSE 3000
COPY --from=builder /app/ ./
CMD ["npm", "start"]

